# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def populate_condition_param_data(apps, schema_editor):
    parameters = [{
        "name": "maximum_area_of_all_boxes",
        "value": 100
    },{
        "name": "average_volume_of_user_boxes",
        "value": 1000
    },{
        "name": "no_of_boxes_added_in_a_week",
        "value": 100
    },{
        "name": "no_of_boxes_added_in_a_week_by_a_user",
        "value": 50
    }];

    ConditionParameter = apps.get_model('inventory', 'ConditionParameter')
    for param in parameters:
        val = ConditionParameter.objects.create(param)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_condition_param_data, migrations.RunPython.noop)
    ]
